name: Code analysis

on:
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  pmd-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: 25

      - uses: pmd/pmd-github-action@d9c1f3c5940cbf5923f1354e83fa858b4496ebaa # v2
        id: pmd
        with:
          rulesets: '.github/pmd-ruleset.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false

      - name: Fail build if there are violations
        if: always()
        run: |
          VIOLATIONS="${{ steps.pmd.outputs.violations }}"
          if [ -n "$VIOLATIONS" ] && [ "$VIOLATIONS" != "0" ]; then
            echo "PMD found $VIOLATIONS violations"
            exit 1
          fi
